[WIP] Utility library for remapping the output of third party services to Steamship model objects
nludb/python-client pull request #97
Opened 2022-06-11 20:42 UTC by eob

2022-06-13 09:07 UTC, EniasCailliau requested changes
Love the functionality! Discovery of these tools will be key for our users.

Had a few questions regarding the use of the `Mapping` definition. Looking forward to your thoughts.

2022-06-13 09:07 UTC, EniasCailliau commented on src/steamship/utils/dict_mapper.py
> +            if key < 0 or key >= len(pointer):
```suggestion
            if not 0 <= key < len(pointer):
```
Just fancy Python

2022-06-13 09:07 UTC, EniasCailliau commented on src/steamship/utils/dict_mapper.py
> +            pointer = pointer.get(key, None)
```suggestion
            pointer = pointer[key]
```

We can use pointer[key] here as we checked if key is present before.

2022-06-13 09:07 UTC, EniasCailliau commented on src/steamship/utils/dict_mapper.py
> +    ret = {key: mappings[key].resolve_against(input_dict) for key in mappings}
```suggestion
    ret = {key: mapping.resolve_against(input_dict) for key, mapping in mappings.items()}
```

2022-06-13 09:07 UTC, EniasCailliau commented on src/steamship/utils/dict_mapper.py
> +    return ret
```suggestion
    return ret if into_base_model is None else into_base_model(**ret)
```

2022-06-13 13:29 UTC, dkolas requested changes
I understand the spirit of what you're after here, because this bit is really the only thing that has to be reimplemented per HF plugin.  However:

1 - Is this declarative way actually better than just writing the few lines of python? Below is the relevant method in the zero shot classifier plugin:
```
 def make_tags_from_response(self, response, block_len) -> List[Tag.CreateRequest]:
        tags = []
        for i, label in enumerate(response['labels']):
            tags.append(Tag.CreateRequest(kind=self.config.tag_kind,
                                          name= label,
                                          startIdx=0,
                                          endIdx=block_len,
                                          value={'score': response['scores'][i]}))
        return tags
```
It's shorter than your example, and there's nothing new to learn.

2 - Should we be trying to add this right now?  It feels like a new (albeit small) layer atop the data model that I'm not sure we can justify quite yet.

2022-06-14 18:08 UTC, eob commented
Hrm - yeah, @dkolas I think you might be right. 

The thing that spawned this was that the output of some third-party taggers like OneAI & NLPCloud have a slightly different structure PER model - and each has >10 models. And collapsing the imperative code into declarative code made it clearer what was the same, and what was different, between the responses....

But at the end of the day if it's the same amount of code required.. perhaps it's just needless indirection. Will close this PR without merge and have a go at implementing manually to see how it feels

2022-06-14 18:08 UTC, closed without merging